### ISSUE TITLE
 TypeError: Cannot read property 'root' of undefined

### ISSUE THREAD

**Issue by mckenzieja** [zencashio/z-nomp#155]
```
z-nomp/node_modules/stratum-pool/lib/merkleTree.js:8
   return result._65.root;
 TypeError: Cannot read property 'root' of undefined

```
I'm thinking it's because no workers are requesting shares?

Solutions attempted:
- deleted node_modules, ran npm update.
- Restored config-example.json

All other modules report running but whenever the poolspawner spawns a worker, it throws the above error.

**Comment by mckenzieja** [comment]
SOLVED

Ran znomp as root. 

Dont do that.

**Comment by mckenzieja** [comment]
Actually still an issue.

**Comment by howie50417** [comment]
I have the same error

**Comment by howie50417** [comment]
I modify
return result._65.root;
to
return result._1.root;
then I can run up

**Comment by mckenzieja** [comment]
How viable is that solution?

**Comment by joshuayabut** [comment]
I'm working on this now...

**Comment by joshuayabut** [comment]
Could you all test this commit out? https://github.com/z-classic/node-stratum-pool/compare/test-hash-lookup?expand=1

You'll need to update this file `node_modules/stratum-pool/lib/merkleTree.js` with the one here: https://github.com/z-classic/node-stratum-pool/blob/75a1c90d6de131e1469ee8617bf045a054cedc03/lib/merkleTree.js

**Comment by howie50417** [comment]
After patch this,
I can run z-nomp without jump exception

**Comment by joshuayabut** [comment]
Great to hear... I'll merge this in then.

For anybody else wanting to use this:
`rm -rf node_modules`
`npm update`
`npm install`

**Comment by mckenzieja** [comment]
Seemed to do the trick. Spent hours pouring over stratum's dependencies.
