### ISSUE TITLE
ZCOIN (XZC) with z-nomp

### ISSUE THREAD

**Issue by GianniExplore** [zencashio/z-nomp#156]
I've read that someone has managed to activate ZCOIN with z-nomp

Ocminer has a fork of NOMP working for Zcoin's new algo 
https://github.com/ocminer/node-multi-hashing-xzc

but 
_[zcoin] Cannot run a pool for unsupported algorithm "lyra2Z"_

what's wrong ?
coins/zcoin.json
{
"name": "zcoin",
"symbol": "xzc",
"algorithm": "lyra2Z",
"requireShielding": false
}

install https://github.com/ocminer/node-multi-hashing-xzc
using npm 0.12.8

npm install multi-hashing

npm WARN package.json multi-hashing-test@0.0.9 No license field.
npm WARN cannot run in wd multi-hashing@0.0.4 node-gyp rebuild (wd=/home/user/z-nomp-zcoin/node-multi-hashing-xzc/node_modules/multi-hashing)
multi-hashing@0.0.4 node_modules/multi-hashing
└── bindings@1.2.1

then  in 
_node_modules/stratum-pool/lib/algoProperties.js_
var ev = require('multi-hashing');

but what are informations of lyra2z?

**Comment by aayanl** [comment]
Z-NOMP is meant only for equihash coins, try with the standard NOMP
